### ISSUE TITLE
Your Uploads showing Status: failed Message: null in heroku

### ISSUE THREAD

**Issue by heero74** [cloud-transfer/cloud-transfer-backend#17]
I have deployed the master branch on heroku and already configured client_id,  client_secret and redirect_uri when I tried to create a New Upload it saied it was successful but when I checked Your Uploads it showed failed. I then checked heroku logs and found this

2019-02-21T16:16:36.816449+00:00 app[web.1]: 2019-02-21 16:16:36.815 ERROR 4 --- [pool-1-thread-1] c.g.d.s.u.drive.ResumableDriveUploader   : null
2019-02-21T16:16:36.816467+00:00 app[web.1]: 
2019-02-21T16:16:36.816468+00:00 app[web.1]: java.lang.NullPointerException: null
2019-02-21T16:16:36.816473+00:00 app[web.1]: 	at com.github.dhaval_mehta.savetogoogledrive.uploader.drive.DriveUploader.uploadPartially(DriveUploader.java:78) ~[classes!/:1.0]
2019-02-21T16:16:36.816475+00:00 app[web.1]: 	at com.github.dhaval_mehta.savetogoogledrive.uploader.drive.ResumableDriveUploader.upload(ResumableDriveUploader.java:56) ~[classes!/:1.0]
2019-02-21T16:16:36.816476+00:00 app[web.1]: 	at com.github.dhaval_mehta.savetogoogledrive.uploader.UploadTask.run(UploadTask.java:23) [classes!/:1.0]

I have not changed anything yet so I am not sure where it went wrong a little help would be appreciated.

**Comment by hiiro74** [comment]
Never mind forgot to add google drive api in scopes its fixed now. please close this.

**Comment by heero74** [comment]
Fixed this, forgot to add Google Drive API in scrope to OAuth. Closing.
